# Generated by Django 6.1.1 on 2026-09-06 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва страви')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна (грн)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/', verbose_name='Фото')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наявності')),
                ('is_spicy', models.BooleanField(default=False, verbose_name='Гостра страва')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Вегетаріанська')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='restaurant.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Страва',
                'verbose_name_plural': 'Страви',
                'ordering': ['-created_at'],
            },
        ),
    ]
